### ISSUE TITLE
Startup failure

### ISSUE THREAD

**Issue by GatVlieg** [Ken98045/On-Guard#1]
Really no idea here... Using GentlePumpkin's version just fine...

```
PLATFORM VERSION INFO
	Windows 			: 10.0.19041.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4084.0 built by: NET48REL1
	clr.dll 			: 4.8.4180.0 built by: NET48REL1LAST_B
	dfdll.dll 			: 4.8.4084.0 built by: NET48REL1
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/On-Guard-master/Setup/On%20Guard.application
	Application url			: file:///C:/On-Guard-master/Setup/Application%20Files/On%20Guard_0_1_0_2/On%20Guard.exe.manifest

IDENTITIES
	Deployment Identity		: On Guard.application, Version=0.1.0.2, Culture=en-US, PublicKeyToken=0000000000000000, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\On-Guard-master\Setup\On Guard.application resulted in exception. Following failure messages were detected:
		+ Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		+ File, On Guard.exe.manifest, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [2020/08/07 10:46:37] : Activation of C:\On-Guard-master\Setup\On Guard.application has started.
	* [2020/08/07 10:46:37] : Processing of deployment manifest has successfully completed.
	* [2020/08/07 10:46:37] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2020/08/07 10:46:37] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, On Guard.exe.manifest, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.


```

**Comment by Ken98045** [comment]
I know that the first version failed with a hash verify failure due to Github changing LFs in the manifest files to CRLF.  That was fixed (I think) in a second release.  However, this appears to be another problem.  I will try to fix this soon if I can duplicate it.  It is probably some sort of "publish"/setup file generation error, but I can't be sure without looking into it.

Right now I am in the middle of adding a feature to allow boundary drag adjustment of areas of interest.  That feature will probably take another day or so to get right.  I'll get on this as soon as I get that working.  Expect an update by 8/10/20.

Sorry about the problem.  Please stay tuned.  Hopefully, you will find this useful.

**Comment by GatVlieg** [comment]
Hi Ken

No worries. Thanks for looking into this.  I will test for you if I can,
but do know that I really have no damn ide what I am doing, although I am
generally good at following instructions (so says me wife!)

I just downloaded the ZIP (using the provided GitHub option) & extracted
via WinRAR, read the Word doc & then voila, nuffin' Happy bug hunting.

Thanks
Johan

**Comment by Ken98045** [comment]
I would prefer someone with no “damn ide” since I know too much about it and I may automatically avoid problems other people can find because they aren’t familiar with the app

 

Thanks for trying this.  You are one of the first.

**Comment by Ken98045** [comment]
I put a new version of the software on Github.  I should now install correctly.  Note that this fix also includes the ability to freely resize areas of interest.  The .docx readme file has been updated as well.

 

Please let me know if there are any further problems.  Hopefully you can at least get it installing.

**Comment by GatVlieg** [comment]
Hi

I managed to install it successfully, so that bug can be closed.

Some new issues, and I'm going from memory so please forgive:
 - SETUP:  A screen is presented where one has to specify the location of
the AI nd the port
Assuming I understood this correct, I would recommend changing the word AI
to DEEPSTACK AI, reason being that most folks come to your software via
GentlePumkin's software that is in fact named AI Tool Some confusion can
arise; it did with me for a few seconds
 - E-MAIL: Requires a user name & password. I double checked with my BI
setup, and I definitely do NOT have to specify a user name & password. I
had to however enter something to get past this screen. My ability to send
e-mail via my ISP's server is linked to my ISP account / modem.
 - E-MAIL: Recommend a "test" button of some kind

Successfully completed the setup, and got the message it was going to shut
down (or I had to close it) and restart the app; did so.
Using the created shortcut to relaunch the app results in nothing.
And that is where I ended... An inability to start the software up again...

Thanks
Johan

**Comment by Ken98045** [comment]
Yes, it is DeepStack.  I said AI because there is a good chance I will be supporting Amazon’s Rekognition AI as well.  

About 90% of the time you do need an email password, but not always.  Outlook does have a box for “My outgoing email server requires a password” for a reason I guess.  I’ll make the email stuff optional.   I will add a Test button for it.

 

Hmm.  I don’t know about the link not working.  I will look into that.  Microsoft install is it to someplace weird, not the usual “Program Files” directory.  I don’t know why it didn’t give me an option.  Here is where the link ended up on mine: C:\Users\MyUserNameYoursWillVary\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\On Guard\On Guard.  You should try double clicking on that directly.  I’m not sure where it put the executable itself.  I’ll look into it later today.  Hopefully I will get back to you by the end of the day at the latest.

**Comment by Ken98045** [comment]
I’m sorry for your difficulties.  I do try to test this on a clean machine.  However, every Windows installation is different (I did work at Microsoft on Windows many years ago).  

 

The installer tool I was using made it really difficult to debug installation issues.  I have update the project with a different installer.  Hopefully this one will be less prone to problems, or if it does have problems it will be easier to troubleshoot.   The setup program will have a little different look and feel too.

 

I also made a couple of the changes you suggested in the UI and setup steps.  You will now be required to only enter the email server.  You can leave the user and user password blank.  I updated  the title on the AI setup screen to make reference to DeepStack.

 

I know that this is starting to be a pain for you.  However, if you could download from Github and run the Setup.exe (still under the Setup directory) that would be very helpful.

 

Since you are one of the first testers you are definitely exploding the minefield.  I hope to add enough new features to make this useful to you.   I think it is getting very close to that point.

**Comment by GatVlieg** [comment]
Hi Ken

No worries. Issues are to be expected.
I'll test later today.

Thanks
Johan

**Comment by Ken98045** [comment]
Fixed
