### ISSUE TITLE
Alpha Release

### ISSUE THREAD

**Issue by grannysmith59** [Ken98045/On-Guard#14]
Hi Ken, me again, I just received this error message:
![Capture](https://user-images.githubusercontent.com/53004856/110846804-1dbb6580-82a4-11eb-9269-a6aee7266e35.JPG)

Log reports "2021.03.11 19:44:31:3463 - The keyword 'asynchronous processing' is not supported on this platform."

I was flicking through captured frames, and the error appeared when a person was detected

I'm using the latest .NET 5.04 on Server 2016, the same machine as v1.8 was running fine on.

Strange that the error message mentions C:\Onguardv2 when that's not where it's installed.

Earlier I had turned on "Use XML data", but then OnGuard crashed and I had to do a partial setup again (setup DeepStack IP, email and one camera), I was then able to turn off "Use XML data", restart, and then all of my other cameras appeared.

Also "Areas of interest" do not display when no image exists for that camera (even after taking a snapshot from Live)

**Comment by Ken98045** [comment]
I'll look at it tonight or tomorrowKenFrom: grannysmith59 ***@***.***>Sent: Thursday, March 11, 2021, 12:13 PMTo: Ken98045/On-GuardCc: SubscribedSubject: [Ken98045/On-Guard] Alpha Release (#14)Hi Ken, me again, I just received this error message:Log reports "2021.03.11 19:44:31:3463 - The keyword 'asynchronous processing' is not supported on this platform."I was flicking through captured frames, and the error appeared when a person was detectedI'm using the latest .NET 5.04 on Server 2016, the same machine as v1.8 was running fine on.Strange that the error message mentions C:\Onguardv2 when that's not where it's installed.Earlier I had turned on "Use XML data", but then OnGuard crashed and I had to do a partial setup again (setup DeepStack IP, email and one camera), I was then able to turn off "Use XML data", restart, and then all of my other cameras appeared.Also "Areas of interest" do not display when no image exists for that camera (even after taking a snapshot from Live)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Ken98045** [comment]
The Microsoft support for the tools (which are supposedly new and improved) don't support the database stuff in precisely the same way. To get around this go to Application Setting. Look at the database connection string section and click on Use Default.  When you click OK this problem should go away. KenFrom: grannysmith59 ***@***.***>Sent: Thursday, March 11, 2021, 12:13 PMTo: Ken98045/On-GuardCc: SubscribedSubject: [Ken98045/On-Guard] Alpha Release (#14)Hi Ken, me again, I just received this error message:Log reports "2021.03.11 19:44:31:3463 - The keyword 'asynchronous processing' is not supported on this platform."I was flicking through captured frames, and the error appeared when a person was detectedI'm using the latest .NET 5.04 on Server 2016, the same machine as v1.8 was running fine on.Strange that the error message mentions C:\Onguardv2 when that's not where it's installed.Earlier I had turned on "Use XML data", but then OnGuard crashed and I had to do a partial setup again (setup DeepStack IP, email and one camera), I was then able to turn off "Use XML data", restart, and then all of my other cameras appeared.Also "Areas of interest" do not display when no image exists for that camera (even after taking a snapshot from Live)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by grannysmith59** [comment]
Hi Ken, the message only appears when show object rectangles is turned on.

Alan

**Comment by Ken98045** [comment]
I will take a look later tonight.  I haven’t been able to get much computer time in in the last week or so.  Too much going on around here.

**Comment by Ken98045** [comment]
Sorry for the delay in a full response.  Please see below

**Comment by grannysmith59** [comment]
Everything seems OK with the latest release, although I haven't tried the xml storage yet, I'll stick with the registry.

I thought that it copied the current settings to an xml file.

Thanks for all of your work,
Alan
